// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBshehTuWmMh51WLhA9I9T53wp7AvBO-EM',
    appId: '1:386795108636:web:d5d4c59df77826b4e6e2d9',
    messagingSenderId: '386795108636',
    projectId: 'koi1-9a320',
    authDomain: 'koi1-9a320.firebaseapp.com',
    storageBucket: 'koi1-9a320.firebasestorage.app',
    measurementId: 'G-Q9B5WG3WEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKIZ45mQHt6SGDh2F0ScrG5Gzh4y78GW0',
    appId: '1:386795108636:android:a5bfe5bd55b03fb4e6e2d9',
    messagingSenderId: '386795108636',
    projectId: 'koi1-9a320',
    storageBucket: 'koi1-9a320.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUG8mvCM5sDnmhiZ6mS0pUGaD3Bvl3Bc',
    appId: '1:386795108636:ios:d5105317aabced57e6e2d9',
    messagingSenderId: '386795108636',
    projectId: 'koi1-9a320',
    storageBucket: 'koi1-9a320.firebasestorage.app',
    iosBundleId: 'com.example.koi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpUG8mvCM5sDnmhiZ6mS0pUGaD3Bvl3Bc',
    appId: '1:386795108636:ios:d5105317aabced57e6e2d9',
    messagingSenderId: '386795108636',
    projectId: 'koi1-9a320',
    storageBucket: 'koi1-9a320.firebasestorage.app',
    iosBundleId: 'com.example.koi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBshehTuWmMh51WLhA9I9T53wp7AvBO-EM',
    appId: '1:386795108636:web:377fe12d1e36cd3ce6e2d9',
    messagingSenderId: '386795108636',
    projectId: 'koi1-9a320',
    authDomain: 'koi1-9a320.firebaseapp.com',
    storageBucket: 'koi1-9a320.firebasestorage.app',
    measurementId: 'G-38Q7K8JBV3',
  );
}
